### ISSUE TITLE
Access Denied Exception 

### ISSUE THREAD

**Issue by blanchardn13** [gsssrao/youtube-8m-videos-frames#1]
I'm trying to use this script to download videos.

I run the command 

`bash downloadmulticategoryvideos.sh 1 selectedcategories.txt`

and it prints 
`AccessDeniedException: 403 nblancha@nd.edu does not have storage.objects.list access to data.yt8m.org.`

Are you still able to use these scripts or are they blocked by the same authentication issues?

**Comment by gsssrao** [comment]
Hi @blanchardn13 , 
This seems to be a [GSUTIL](https://cloud.google.com/storage/docs/gsutil_install) issue. Have you installed it properly?
I just checked the command today, it still works on my system.

**Comment by blanchardn13** [comment]
Thank you for replying so quickly. I tried to reinstall GSUTIL with no luck, but I will keep messing with and try to figure it out. It is a comfort to know the scripts work, thank you for your time.

**Comment by blanchardn13** [comment]
Hi - 
I figured out that extracting the "mid" ID doesn't work with my set up and that's what caused my error. Hopefully helpful to someone else in the future!

**Comment by gsssrao** [comment]
@blanchardn13 , do you mean this line:
https://github.com/gsssrao/youtube-8m-videos-frames/blob/master/downloadcategoryids.sh#L17 
It may be a problem with egrep workin on your OS. What OS are you working on?

**Comment by blanchardn13** [comment]
That's the line - running RHEL 7

**Comment by gsssrao** [comment]
@blanchardn13 Sorry, I was commuting. 

I have modified the repository. Can you check and tell me if the commands work now (You will need to pull the recent changes)?

**Comment by blanchardn13** [comment]
I couldn't get that to work but I modified the commands to 
`mid=$(grep -P "\t$name \(" youtube8mcategories.txt | grep -o "\".*\"" | sed -n 's/"\(.*\)"/\1/p')` 
and that worked (I think i just changed the -E to -P)

**Comment by gsssrao** [comment]
Hey, thanks for mentioning it. I have fixed the repo, it should work now.
The problem was that I was in a different OS while making the repo and didn't test the repo across other OS.
