### ISSUE TITLE
can not download videos

### ISSUE THREAD

**Issue by fushunren** [gsssrao/youtube-8m-videos-frames#10]
when I run the code. happen a error: "curl: (35) gnutls_handshake() failed: Error in the pull function".
Do you know how to solve?
thx

**Comment by gsssrao** [comment]
Hi, 
Sorry for the late reply. I just checked the repo and it seems to work as expected. Can you try again? This issue might could be due to your IP being blocked (due to excessive downloads). Maybe try downloading from a different physical location using a different wifi and it might work.
